### ISSUE TITLE
describe ezStats

### ISSUE THREAD

**Issue by ajmoralesa** [achetverikov/APAstats#2]
Hello, 

I was wondering whether including a `describe.ezstats` function would be interesting. I normally use `ez` package to perform _ANOVAs_ and it would be really helpful to automatize mean ± SD values of the different main and interaction effects from `ezANOVA `provided by `ezStats`. 

Many thanks and congratulations for such a helpful package. 

Antonio

**Comment by achetverikov** [comment]
Hi Antonio - 

Yeah, why not. I'll try to do it tomorrow.

Andrey

**Comment by achetverikov** [comment]
describe.ezstats was added with the last commit - check the help file for some examples
