### ISSUE TITLE
Stupid question maybe: How do I get Latex output?

### ISSUE THREAD

**Issue by Sumidu** [achetverikov/APAstats#5]
When I call the methods in my markdown script, I always get MD output. 
How do I change it to Latex, e.g. in describe.ttest ()?

**Comment by achetverikov** [comment]
Just add `type = 'latex'` to the parameters in the function call

**Comment by Sumidu** [comment]
The function "describe.mean.sd" does not seem to react to this parameter.
describe.mean.sd(variable, type='latex') gives me Markdown output
describe.mean.conf(variable, type='latex') gives me Latex output

**Comment by achetverikov** [comment]
ah, indeed, there was a parameter with the same name in describe.mean.sd
just fixed this, pull the latest version to get an update
